name: Test build
on:
  pull_request:
  workflow_dispatch:
  workflow_call:
jobs:
  Test_build:
    name: Test build
    uses: noelmiller/pelican/.github/workflows/build.yml@pelican_decouple_build_workflow
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      settings: "publishconf.py"
      requirements: "pelican[markdown] typogrify"
      theme: "https://github.com/seanh/sidecar.git"
