name: Deploy
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  Deploy:
    uses: seanh/pelican/.github/workflows/github_pages.yml@pelican_decouple_build_workflow-single-file
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      settings: "publishconf.py"
      requirements: "pelican[markdown] typogrify"
      theme: "https://github.com/seanh/sidecar.git"
      deploy: true
