name: Deploy
on:
  pull_request:
  push:
    branches: ["main"]
  workflow_dispatch:
  workflow_call:
jobs:
  Deploy:
    uses: seanh/pelican/.github/workflows/github_pages.yml@pelican_decouple_build_workflow-single-file
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      settings: "publishconf.py"
      requirements: "pelican[markdown] typogrify"
      theme: "https://github.com/seanh/sidecar.git"
      deploy: github.event_name != "pull_request" && github.ref_type == "branch" && github.ref == "main"
